/* eslint-disable @typescript-eslint/no-explicit-any */
import Footer from '@/components/footer/Footer'
import HeaderSticky from '@/components/header/HeaderSticky'
import type {Metadata} from 'next'
import {Toaster} from 'sonner'
import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body>
        <HeaderSticky />
        {children}

        <Toaster
          theme='light'
          richColors
          position='bottom-right'
          closeButton
          duration={4000}
          expand
        />
        <Footer />
      </body>
    </html>
  )
}
